[build]
  publish = ".next"
  command = "npm ci && npm run build"  # Force clean install of dependencies

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18..20.0"  # Specify the exact version here
