[build]
  publish = ".next"
  command = "npm install --include=dev && npm run build"  # Ensures dev dependencies are installed even in production

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18.20.0"  # Specify the exact version here

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
